/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_get_wasmsearchresult_best_from_c: (a: number) => number;
export const __wbg_get_wasmsearchresult_best_from_r: (a: number) => number;
export const __wbg_get_wasmsearchresult_best_to_c: (a: number) => number;
export const __wbg_get_wasmsearchresult_best_to_r: (a: number) => number;
export const __wbg_get_wasmsearchresult_depth: (a: number) => number;
export const __wbg_get_wasmsearchresult_found: (a: number) => number;
export const __wbg_get_wasmsearchresult_nodes: (a: number) => number;
export const __wbg_get_wasmsearchresult_pv: (a: number) => [number, number];
export const __wbg_get_wasmsearchresult_score: (a: number) => number;
export const __wbg_get_wasmsearchresult_time_ms: (a: number) => number;
export const __wbg_set_wasmsearchresult_best_from_c: (a: number, b: number) => void;
export const __wbg_set_wasmsearchresult_best_from_r: (a: number, b: number) => void;
export const __wbg_set_wasmsearchresult_best_to_c: (a: number, b: number) => void;
export const __wbg_set_wasmsearchresult_best_to_r: (a: number, b: number) => void;
export const __wbg_set_wasmsearchresult_depth: (a: number, b: number) => void;
export const __wbg_set_wasmsearchresult_found: (a: number, b: number) => void;
export const __wbg_set_wasmsearchresult_nodes: (a: number, b: number) => void;
export const __wbg_set_wasmsearchresult_pv: (a: number, b: number, c: number) => void;
export const __wbg_set_wasmsearchresult_score: (a: number, b: number) => void;
export const __wbg_set_wasmsearchresult_time_ms: (a: number, b: number) => void;
export const __wbg_wasmsearchresult_free: (a: number, b: number) => void;
export const ai_move_wasm: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => number;
export const all_legal_moves_flat: (a: number, b: number, c: number) => [number, number];
export const board_hash_wasm: (a: number, b: number, c: number) => [number, number];
export const evaluate_board: (a: number, b: number) => number;
export const game_status_str: (a: number, b: number, c: number) => [number, number];
export const in_check_side: (a: number, b: number, c: number) => number;
export const is_legal_move_wasm: (a: number, b: number, c: number, d: number, e: number, f: number) => number;
export const legal_captures_flat: (a: number, b: number, c: number) => [number, number];
export const perft_wasm: (a: number, b: number, c: number, d: number) => bigint;
export const tt_clear: () => void;
export const set_zobrist_seed: (a: number, b: number) => void;
export const h_reset: () => void;
export const stop: () => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
